### ISSUE TITLE
Fix Merger component

### ISSUE THREAD

**Issue by Valyukhov** [texttree/v-cana-offline#84]
**Description of the task**
На шаге, когда идёт объединение всех стихов нужно проверить не идёт ли перезапись стихов, которые перевёл пользователь и которые лежат в его файловой системе теми стихами, которые приходят их архива во время слияния.

**Criteria for getting fulfilled**
- [x] При слияниии главы в компоненте Merger стихи пользователя не заменяются

**Common decision**
Найти функцию, которая делает слияние импортированной главы в главу в программе и изменить

**Steps to complete**
1. Нужно найти алгоритм в функции, который перезаписывает все стихи из загружаемого архива на все стихи в системе пользователя.
2. Нужно найти все стихи, которые назначены на текущего пользователя.
3. И при слиянии  сделать фильтр  и заменить только стихи, которые не назначены на пользователя.

**New components or functions**

**Optimization components or functions**

**Testing**

Написать тест, в который приходят 2 коллекции - 1 это коллекция стихов, эмулирующий испортируемый файл, второй - это коллекция стихов, которые сохранены в системе.
Успешным результатом теста будет то, что коллекция стихов, которая сохранена в системе после выполнения функции не изменится.
Проверить на вход массив, обьект, пустые значения.

**Comment by Valyukhov** [comment]
@foxprogs сделал описание задачи - так примерно, или нужно более подробно?

**Comment by foxprogs** [comment]
@Valyukhov блок с тестами отличный. Может еще пункт добавить - это пограничные значения. По сути мы же их тестируем. То есть два массива с одинаковым стихом, 2 массива с пропущенным стихом, и то что ты написал, что вместо массива прилетит что-то не то.
